/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "./common";

export interface BeefyPearlStrategyInterface extends utils.Interface {
  functions: {
    "DEFAULT_ADMIN_ROLE()": FunctionFragment;
    "MAX_BPS()": FunctionFragment;
    "STRATEGIST_ROLE()": FunctionFragment;
    "asset()": FunctionFragment;
    "balanceOfAsset()": FunctionFragment;
    "beefy()": FunctionFragment;
    "defaultSlippageBps()": FunctionFragment;
    "divest(uint256)": FunctionFragment;
    "divestAssets(uint256,uint256)": FunctionFragment;
    "getRoleAdmin(bytes32)": FunctionFragment;
    "grantRole(bytes32,address)": FunctionFragment;
    "hasRole(bytes32,address)": FunctionFragment;
    "invest(uint256)": FunctionFragment;
    "investAssets(uint256,uint256)": FunctionFragment;
    "lpToken()": FunctionFragment;
    "pearlRouter()": FunctionFragment;
    "renounceRole(bytes32,address)": FunctionFragment;
    "revokeRole(bytes32,address)": FunctionFragment;
    "setDefaultSlippageBps(uint256)": FunctionFragment;
    "supportsInterface(bytes4)": FunctionFragment;
    "sweep(address)": FunctionFragment;
    "token0()": FunctionFragment;
    "token1()": FunctionFragment;
    "totalLockedValue()": FunctionFragment;
    "vault()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "DEFAULT_ADMIN_ROLE"
      | "MAX_BPS"
      | "STRATEGIST_ROLE"
      | "asset"
      | "balanceOfAsset"
      | "beefy"
      | "defaultSlippageBps"
      | "divest"
      | "divestAssets"
      | "getRoleAdmin"
      | "grantRole"
      | "hasRole"
      | "invest"
      | "investAssets"
      | "lpToken"
      | "pearlRouter"
      | "renounceRole"
      | "revokeRole"
      | "setDefaultSlippageBps"
      | "supportsInterface"
      | "sweep"
      | "token0"
      | "token1"
      | "totalLockedValue"
      | "vault",
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    values?: undefined,
  ): string;

  encodeFunctionData(functionFragment: "MAX_BPS", values?: undefined): string;

  encodeFunctionData(
    functionFragment: "STRATEGIST_ROLE",
    values?: undefined,
  ): string;

  encodeFunctionData(functionFragment: "asset", values?: undefined): string;

  encodeFunctionData(
    functionFragment: "balanceOfAsset",
    values?: undefined,
  ): string;

  encodeFunctionData(functionFragment: "beefy", values?: undefined): string;

  encodeFunctionData(
    functionFragment: "defaultSlippageBps",
    values?: undefined,
  ): string;

  encodeFunctionData(
    functionFragment: "divest",
    values: [BigNumberish],
  ): string;

  encodeFunctionData(
    functionFragment: "divestAssets",
    values: [BigNumberish, BigNumberish],
  ): string;

  encodeFunctionData(
    functionFragment: "getRoleAdmin",
    values: [BytesLike],
  ): string;

  encodeFunctionData(
    functionFragment: "grantRole",
    values: [BytesLike, string],
  ): string;

  encodeFunctionData(
    functionFragment: "hasRole",
    values: [BytesLike, string],
  ): string;

  encodeFunctionData(
    functionFragment: "invest",
    values: [BigNumberish],
  ): string;

  encodeFunctionData(
    functionFragment: "investAssets",
    values: [BigNumberish, BigNumberish],
  ): string;

  encodeFunctionData(functionFragment: "lpToken", values?: undefined): string;

  encodeFunctionData(
    functionFragment: "pearlRouter",
    values?: undefined,
  ): string;

  encodeFunctionData(
    functionFragment: "renounceRole",
    values: [BytesLike, string],
  ): string;

  encodeFunctionData(
    functionFragment: "revokeRole",
    values: [BytesLike, string],
  ): string;

  encodeFunctionData(
    functionFragment: "setDefaultSlippageBps",
    values: [BigNumberish],
  ): string;

  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [BytesLike],
  ): string;

  encodeFunctionData(functionFragment: "sweep", values: [string]): string;

  encodeFunctionData(functionFragment: "token0", values?: undefined): string;

  encodeFunctionData(functionFragment: "token1", values?: undefined): string;

  encodeFunctionData(
    functionFragment: "totalLockedValue",
    values?: undefined,
  ): string;

  encodeFunctionData(functionFragment: "vault", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    data: BytesLike,
  ): Result;

  decodeFunctionResult(functionFragment: "MAX_BPS", data: BytesLike): Result;

  decodeFunctionResult(
    functionFragment: "STRATEGIST_ROLE",
    data: BytesLike,
  ): Result;

  decodeFunctionResult(functionFragment: "asset", data: BytesLike): Result;

  decodeFunctionResult(
    functionFragment: "balanceOfAsset",
    data: BytesLike,
  ): Result;

  decodeFunctionResult(functionFragment: "beefy", data: BytesLike): Result;

  decodeFunctionResult(
    functionFragment: "defaultSlippageBps",
    data: BytesLike,
  ): Result;

  decodeFunctionResult(functionFragment: "divest", data: BytesLike): Result;

  decodeFunctionResult(
    functionFragment: "divestAssets",
    data: BytesLike,
  ): Result;

  decodeFunctionResult(
    functionFragment: "getRoleAdmin",
    data: BytesLike,
  ): Result;

  decodeFunctionResult(functionFragment: "grantRole", data: BytesLike): Result;

  decodeFunctionResult(functionFragment: "hasRole", data: BytesLike): Result;

  decodeFunctionResult(functionFragment: "invest", data: BytesLike): Result;

  decodeFunctionResult(
    functionFragment: "investAssets",
    data: BytesLike,
  ): Result;

  decodeFunctionResult(functionFragment: "lpToken", data: BytesLike): Result;

  decodeFunctionResult(
    functionFragment: "pearlRouter",
    data: BytesLike,
  ): Result;

  decodeFunctionResult(
    functionFragment: "renounceRole",
    data: BytesLike,
  ): Result;

  decodeFunctionResult(functionFragment: "revokeRole", data: BytesLike): Result;

  decodeFunctionResult(
    functionFragment: "setDefaultSlippageBps",
    data: BytesLike,
  ): Result;

  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike,
  ): Result;

  decodeFunctionResult(functionFragment: "sweep", data: BytesLike): Result;

  decodeFunctionResult(functionFragment: "token0", data: BytesLike): Result;

  decodeFunctionResult(functionFragment: "token1", data: BytesLike): Result;

  decodeFunctionResult(
    functionFragment: "totalLockedValue",
    data: BytesLike,
  ): Result;

  decodeFunctionResult(functionFragment: "vault", data: BytesLike): Result;

  events: {
    "RoleAdminChanged(bytes32,bytes32,bytes32)": EventFragment;
    "RoleGranted(bytes32,address,address)": EventFragment;
    "RoleRevoked(bytes32,address,address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "RoleAdminChanged"): EventFragment;

  getEvent(nameOrSignatureOrTopic: "RoleGranted"): EventFragment;

  getEvent(nameOrSignatureOrTopic: "RoleRevoked"): EventFragment;
}

export interface RoleAdminChangedEventObject {
  role: string;
  previousAdminRole: string;
  newAdminRole: string;
}

export type RoleAdminChangedEvent = TypedEvent<
  [string, string, string],
  RoleAdminChangedEventObject
>;

export type RoleAdminChangedEventFilter =
  TypedEventFilter<RoleAdminChangedEvent>;

export interface RoleGrantedEventObject {
  role: string;
  account: string;
  sender: string;
}

export type RoleGrantedEvent = TypedEvent<
  [string, string, string],
  RoleGrantedEventObject
>;

export type RoleGrantedEventFilter = TypedEventFilter<RoleGrantedEvent>;

export interface RoleRevokedEventObject {
  role: string;
  account: string;
  sender: string;
}

export type RoleRevokedEvent = TypedEvent<
  [string, string, string],
  RoleRevokedEventObject
>;

export type RoleRevokedEventFilter = TypedEventFilter<RoleRevokedEvent>;

export interface BeefyPearlStrategy extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;

  attach(addressOrName: string): this;

  deployed(): Promise<this>;

  interface: BeefyPearlStrategyInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>,
  ): Array<TypedListener<TEvent>>;

  listeners(eventName?: string): Array<Listener>;

  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>,
  ): this;

  removeAllListeners(eventName?: string): this;

  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    DEFAULT_ADMIN_ROLE(overrides?: CallOverrides): Promise<[string]>;

    MAX_BPS(overrides?: CallOverrides): Promise<[BigNumber]>;

    STRATEGIST_ROLE(overrides?: CallOverrides): Promise<[string]>;

    asset(overrides?: CallOverrides): Promise<[string]>;

    balanceOfAsset(
      overrides?: CallOverrides,
    ): Promise<[BigNumber] & { assets: BigNumber }>;

    beefy(overrides?: CallOverrides): Promise<[string]>;

    defaultSlippageBps(overrides?: CallOverrides): Promise<[BigNumber]>;

    divest(
      amount: BigNumberish,
      overrides?: Overrides & { from?: string },
    ): Promise<ContractTransaction>;

    divestAssets(
      amount: BigNumberish,
      slippageBps: BigNumberish,
      overrides?: Overrides & { from?: string },
    ): Promise<ContractTransaction>;

    getRoleAdmin(role: BytesLike, overrides?: CallOverrides): Promise<[string]>;

    grantRole(
      role: BytesLike,
      account: string,
      overrides?: Overrides & { from?: string },
    ): Promise<ContractTransaction>;

    hasRole(
      role: BytesLike,
      account: string,
      overrides?: CallOverrides,
    ): Promise<[boolean]>;

    invest(
      amount: BigNumberish,
      overrides?: Overrides & { from?: string },
    ): Promise<ContractTransaction>;

    investAssets(
      amount: BigNumberish,
      slippageBps: BigNumberish,
      overrides?: Overrides & { from?: string },
    ): Promise<ContractTransaction>;

    lpToken(overrides?: CallOverrides): Promise<[string]>;

    pearlRouter(overrides?: CallOverrides): Promise<[string]>;

    renounceRole(
      role: BytesLike,
      account: string,
      overrides?: Overrides & { from?: string },
    ): Promise<ContractTransaction>;

    revokeRole(
      role: BytesLike,
      account: string,
      overrides?: Overrides & { from?: string },
    ): Promise<ContractTransaction>;

    setDefaultSlippageBps(
      slippageBps: BigNumberish,
      overrides?: Overrides & { from?: string },
    ): Promise<ContractTransaction>;

    supportsInterface(
      interfaceId: BytesLike,
      overrides?: CallOverrides,
    ): Promise<[boolean]>;

    sweep(
      token: string,
      overrides?: Overrides & { from?: string },
    ): Promise<ContractTransaction>;

    token0(overrides?: CallOverrides): Promise<[string]>;

    token1(overrides?: CallOverrides): Promise<[string]>;

    totalLockedValue(overrides?: CallOverrides): Promise<[BigNumber]>;

    vault(overrides?: CallOverrides): Promise<[string]>;
  };

  DEFAULT_ADMIN_ROLE(overrides?: CallOverrides): Promise<string>;

  MAX_BPS(overrides?: CallOverrides): Promise<BigNumber>;

  STRATEGIST_ROLE(overrides?: CallOverrides): Promise<string>;

  asset(overrides?: CallOverrides): Promise<string>;

  balanceOfAsset(overrides?: CallOverrides): Promise<BigNumber>;

  beefy(overrides?: CallOverrides): Promise<string>;

  defaultSlippageBps(overrides?: CallOverrides): Promise<BigNumber>;

  divest(
    amount: BigNumberish,
    overrides?: Overrides & { from?: string },
  ): Promise<ContractTransaction>;

  divestAssets(
    amount: BigNumberish,
    slippageBps: BigNumberish,
    overrides?: Overrides & { from?: string },
  ): Promise<ContractTransaction>;

  getRoleAdmin(role: BytesLike, overrides?: CallOverrides): Promise<string>;

  grantRole(
    role: BytesLike,
    account: string,
    overrides?: Overrides & { from?: string },
  ): Promise<ContractTransaction>;

  hasRole(
    role: BytesLike,
    account: string,
    overrides?: CallOverrides,
  ): Promise<boolean>;

  invest(
    amount: BigNumberish,
    overrides?: Overrides & { from?: string },
  ): Promise<ContractTransaction>;

  investAssets(
    amount: BigNumberish,
    slippageBps: BigNumberish,
    overrides?: Overrides & { from?: string },
  ): Promise<ContractTransaction>;

  lpToken(overrides?: CallOverrides): Promise<string>;

  pearlRouter(overrides?: CallOverrides): Promise<string>;

  renounceRole(
    role: BytesLike,
    account: string,
    overrides?: Overrides & { from?: string },
  ): Promise<ContractTransaction>;

  revokeRole(
    role: BytesLike,
    account: string,
    overrides?: Overrides & { from?: string },
  ): Promise<ContractTransaction>;

  setDefaultSlippageBps(
    slippageBps: BigNumberish,
    overrides?: Overrides & { from?: string },
  ): Promise<ContractTransaction>;

  supportsInterface(
    interfaceId: BytesLike,
    overrides?: CallOverrides,
  ): Promise<boolean>;

  sweep(
    token: string,
    overrides?: Overrides & { from?: string },
  ): Promise<ContractTransaction>;

  token0(overrides?: CallOverrides): Promise<string>;

  token1(overrides?: CallOverrides): Promise<string>;

  totalLockedValue(overrides?: CallOverrides): Promise<BigNumber>;

  vault(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    DEFAULT_ADMIN_ROLE(overrides?: CallOverrides): Promise<string>;

    MAX_BPS(overrides?: CallOverrides): Promise<BigNumber>;

    STRATEGIST_ROLE(overrides?: CallOverrides): Promise<string>;

    asset(overrides?: CallOverrides): Promise<string>;

    balanceOfAsset(overrides?: CallOverrides): Promise<BigNumber>;

    beefy(overrides?: CallOverrides): Promise<string>;

    defaultSlippageBps(overrides?: CallOverrides): Promise<BigNumber>;

    divest(amount: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>;

    divestAssets(
      amount: BigNumberish,
      slippageBps: BigNumberish,
      overrides?: CallOverrides,
    ): Promise<void>;

    getRoleAdmin(role: BytesLike, overrides?: CallOverrides): Promise<string>;

    grantRole(
      role: BytesLike,
      account: string,
      overrides?: CallOverrides,
    ): Promise<void>;

    hasRole(
      role: BytesLike,
      account: string,
      overrides?: CallOverrides,
    ): Promise<boolean>;

    invest(amount: BigNumberish, overrides?: CallOverrides): Promise<void>;

    investAssets(
      amount: BigNumberish,
      slippageBps: BigNumberish,
      overrides?: CallOverrides,
    ): Promise<void>;

    lpToken(overrides?: CallOverrides): Promise<string>;

    pearlRouter(overrides?: CallOverrides): Promise<string>;

    renounceRole(
      role: BytesLike,
      account: string,
      overrides?: CallOverrides,
    ): Promise<void>;

    revokeRole(
      role: BytesLike,
      account: string,
      overrides?: CallOverrides,
    ): Promise<void>;

    setDefaultSlippageBps(
      slippageBps: BigNumberish,
      overrides?: CallOverrides,
    ): Promise<void>;

    supportsInterface(
      interfaceId: BytesLike,
      overrides?: CallOverrides,
    ): Promise<boolean>;

    sweep(token: string, overrides?: CallOverrides): Promise<void>;

    token0(overrides?: CallOverrides): Promise<string>;

    token1(overrides?: CallOverrides): Promise<string>;

    totalLockedValue(overrides?: CallOverrides): Promise<BigNumber>;

    vault(overrides?: CallOverrides): Promise<string>;
  };

  filters: {
    "RoleAdminChanged(bytes32,bytes32,bytes32)"(
      role?: BytesLike | null,
      previousAdminRole?: BytesLike | null,
      newAdminRole?: BytesLike | null,
    ): RoleAdminChangedEventFilter;
    RoleAdminChanged(
      role?: BytesLike | null,
      previousAdminRole?: BytesLike | null,
      newAdminRole?: BytesLike | null,
    ): RoleAdminChangedEventFilter;

    "RoleGranted(bytes32,address,address)"(
      role?: BytesLike | null,
      account?: string | null,
      sender?: string | null,
    ): RoleGrantedEventFilter;
    RoleGranted(
      role?: BytesLike | null,
      account?: string | null,
      sender?: string | null,
    ): RoleGrantedEventFilter;

    "RoleRevoked(bytes32,address,address)"(
      role?: BytesLike | null,
      account?: string | null,
      sender?: string | null,
    ): RoleRevokedEventFilter;
    RoleRevoked(
      role?: BytesLike | null,
      account?: string | null,
      sender?: string | null,
    ): RoleRevokedEventFilter;
  };

  estimateGas: {
    DEFAULT_ADMIN_ROLE(overrides?: CallOverrides): Promise<BigNumber>;

    MAX_BPS(overrides?: CallOverrides): Promise<BigNumber>;

    STRATEGIST_ROLE(overrides?: CallOverrides): Promise<BigNumber>;

    asset(overrides?: CallOverrides): Promise<BigNumber>;

    balanceOfAsset(overrides?: CallOverrides): Promise<BigNumber>;

    beefy(overrides?: CallOverrides): Promise<BigNumber>;

    defaultSlippageBps(overrides?: CallOverrides): Promise<BigNumber>;

    divest(
      amount: BigNumberish,
      overrides?: Overrides & { from?: string },
    ): Promise<BigNumber>;

    divestAssets(
      amount: BigNumberish,
      slippageBps: BigNumberish,
      overrides?: Overrides & { from?: string },
    ): Promise<BigNumber>;

    getRoleAdmin(
      role: BytesLike,
      overrides?: CallOverrides,
    ): Promise<BigNumber>;

    grantRole(
      role: BytesLike,
      account: string,
      overrides?: Overrides & { from?: string },
    ): Promise<BigNumber>;

    hasRole(
      role: BytesLike,
      account: string,
      overrides?: CallOverrides,
    ): Promise<BigNumber>;

    invest(
      amount: BigNumberish,
      overrides?: Overrides & { from?: string },
    ): Promise<BigNumber>;

    investAssets(
      amount: BigNumberish,
      slippageBps: BigNumberish,
      overrides?: Overrides & { from?: string },
    ): Promise<BigNumber>;

    lpToken(overrides?: CallOverrides): Promise<BigNumber>;

    pearlRouter(overrides?: CallOverrides): Promise<BigNumber>;

    renounceRole(
      role: BytesLike,
      account: string,
      overrides?: Overrides & { from?: string },
    ): Promise<BigNumber>;

    revokeRole(
      role: BytesLike,
      account: string,
      overrides?: Overrides & { from?: string },
    ): Promise<BigNumber>;

    setDefaultSlippageBps(
      slippageBps: BigNumberish,
      overrides?: Overrides & { from?: string },
    ): Promise<BigNumber>;

    supportsInterface(
      interfaceId: BytesLike,
      overrides?: CallOverrides,
    ): Promise<BigNumber>;

    sweep(
      token: string,
      overrides?: Overrides & { from?: string },
    ): Promise<BigNumber>;

    token0(overrides?: CallOverrides): Promise<BigNumber>;

    token1(overrides?: CallOverrides): Promise<BigNumber>;

    totalLockedValue(overrides?: CallOverrides): Promise<BigNumber>;

    vault(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    DEFAULT_ADMIN_ROLE(
      overrides?: CallOverrides,
    ): Promise<PopulatedTransaction>;

    MAX_BPS(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    STRATEGIST_ROLE(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    asset(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    balanceOfAsset(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    beefy(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    defaultSlippageBps(
      overrides?: CallOverrides,
    ): Promise<PopulatedTransaction>;

    divest(
      amount: BigNumberish,
      overrides?: Overrides & { from?: string },
    ): Promise<PopulatedTransaction>;

    divestAssets(
      amount: BigNumberish,
      slippageBps: BigNumberish,
      overrides?: Overrides & { from?: string },
    ): Promise<PopulatedTransaction>;

    getRoleAdmin(
      role: BytesLike,
      overrides?: CallOverrides,
    ): Promise<PopulatedTransaction>;

    grantRole(
      role: BytesLike,
      account: string,
      overrides?: Overrides & { from?: string },
    ): Promise<PopulatedTransaction>;

    hasRole(
      role: BytesLike,
      account: string,
      overrides?: CallOverrides,
    ): Promise<PopulatedTransaction>;

    invest(
      amount: BigNumberish,
      overrides?: Overrides & { from?: string },
    ): Promise<PopulatedTransaction>;

    investAssets(
      amount: BigNumberish,
      slippageBps: BigNumberish,
      overrides?: Overrides & { from?: string },
    ): Promise<PopulatedTransaction>;

    lpToken(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    pearlRouter(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    renounceRole(
      role: BytesLike,
      account: string,
      overrides?: Overrides & { from?: string },
    ): Promise<PopulatedTransaction>;

    revokeRole(
      role: BytesLike,
      account: string,
      overrides?: Overrides & { from?: string },
    ): Promise<PopulatedTransaction>;

    setDefaultSlippageBps(
      slippageBps: BigNumberish,
      overrides?: Overrides & { from?: string },
    ): Promise<PopulatedTransaction>;

    supportsInterface(
      interfaceId: BytesLike,
      overrides?: CallOverrides,
    ): Promise<PopulatedTransaction>;

    sweep(
      token: string,
      overrides?: Overrides & { from?: string },
    ): Promise<PopulatedTransaction>;

    token0(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    token1(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    totalLockedValue(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    vault(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
