/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  AffineGovernable,
  AffineGovernableInterface,
} from "../AffineGovernable";

const _abi = [
  {
    inputs: [],
    name: "governance",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class AffineGovernable__factory {
  static readonly abi = _abi;

  static createInterface(): AffineGovernableInterface {
    return new utils.Interface(_abi) as AffineGovernableInterface;
  }

  static connect(
    address: string,
    signerOrProvider: Signer | Provider,
  ): AffineGovernable {
    return new Contract(address, _abi, signerOrProvider) as AffineGovernable;
  }
}
