/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type { DummyRelay, DummyRelayInterface } from "../DummyRelay";

const _abi = [
  {
    inputs: [],
    name: "trustedForwarder",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class DummyRelay__factory {
  static readonly abi = _abi;
  static createInterface(): DummyRelayInterface {
    return new utils.Interface(_abi) as DummyRelayInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): DummyRelay {
    return new Contract(address, _abi, signerOrProvider) as DummyRelay;
  }
}
