/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IStrategyManager,
  IStrategyManagerInterface,
} from "../IStrategyManager";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
      {
        internalType: "address",
        name: "",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    name: "depositIntoStrategy",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IStrategyManager__factory {
  static readonly abi = _abi;
  static createInterface(): IStrategyManagerInterface {
    return new utils.Interface(_abi) as IStrategyManagerInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IStrategyManager {
    return new Contract(address, _abi, signerOrProvider) as IStrategyManager;
  }
}
