/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  RebalanceModule,
  RebalanceModuleInterface,
} from "../RebalanceModule";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "contract AffineVault",
        name: "vault",
        type: "address",
      },
    ],
    name: "Rebalance",
    type: "event",
  },
  {
    inputs: [],
    name: "rebalance",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class RebalanceModule__factory {
  static readonly abi = _abi;

  static createInterface(): RebalanceModuleInterface {
    return new utils.Interface(_abi) as RebalanceModuleInterface;
  }

  static connect(
    address: string,
    signerOrProvider: Signer | Provider,
  ): RebalanceModule {
    return new Contract(address, _abi, signerOrProvider) as RebalanceModule;
  }
}
