/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  RebalanceStorage,
  RebalanceStorageInterface,
} from "../RebalanceStorage";

const _abi = [
  {
    inputs: [],
    name: "governance",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "rebalanceModule",
    outputs: [
      {
        internalType: "contract RebalanceModule",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_rebalanceModule",
        type: "address",
      },
    ],
    name: "setRebalanceModule",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class RebalanceStorage__factory {
  static readonly abi = _abi;
  static createInterface(): RebalanceStorageInterface {
    return new utils.Interface(_abi) as RebalanceStorageInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): RebalanceStorage {
    return new Contract(address, _abi, signerOrProvider) as RebalanceStorage;
  }
}
