/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {Contract, Signer, utils} from "ethers";
import type {Provider} from "@ethersproject/providers";
import type {VaultErrors, VaultErrorsInterface} from "../VaultErrors";

const _abi = [
  {
    inputs: [],
    name: "OnlyEscrow",
    type: "error",
  },
  {
    inputs: [],
    name: "OnlyWormholeRouter",
    type: "error",
  },
  {
    inputs: [],
    name: "ProfitUnlocking",
    type: "error",
  },
  {
    inputs: [],
    name: "SharesExceedBalance",
    type: "error",
  },
  {
    inputs: [],
    name: "TooManyStrategyBps",
    type: "error",
  },
  {
    inputs: [],
    name: "TvlLimitReached",
    type: "error",
  },
  {
    inputs: [],
    name: "ZeroShares",
    type: "error",
  },
] as const;

export class VaultErrors__factory {
  static readonly abi = _abi;

  static createInterface(): VaultErrorsInterface {
    return new utils.Interface(_abi) as VaultErrorsInterface;
  }

  static connect(
    address: string,
    signerOrProvider: Signer | Provider,
  ): VaultErrors {
    return new Contract(address, _abi, signerOrProvider) as VaultErrors;
  }
}
