name: Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.13.1'

      - name: Install Yarn 1.22.1
        run: npm install -g yarn@1.22.1

      - name: Install dependencies
        run: yarn install

      - name: Update version
        run: yarn version --patch --no-git-tag-version

      - name: Create version.ts
        run: |
          VERSION=$(node -p "require('./package.json').version")
          echo "export const AFFINE_SDK_VERSION = '$VERSION';" > src/version.ts      

      - name: Build the package
        run: yarn build

      - name: Commit and push version update
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add package.json yarn.lock dist
          git commit -m "Updated version"
          git push origin main
